# Generated by Django 3.2.9 on 2021-11-08 19:14

import Restapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('ranking', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=Restapi.models.Users.upload_photo)),
                ('resume', models.ImageField(blank=True, null=True, upload_to=Restapi.models.Users.upload_file)),
            ],
        ),
    ]
