# Generated by Django 3.2.9 on 2021-11-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('picture', models.ImageField(blank=True, upload_to='my_picture')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload_photo'),
        ),
    ]
