# Generated by Django 3.2.9 on 2021-11-09 12:38

import Restapi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restapi', '0002_auto_20211109_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to=Restapi.models.profile.nameFile),
        ),
    ]
